### ISSUE TITLE
How to use this with TypeScript?

### ISSUE THREAD

**Issue by JanekNaymspace** [Calvin-LL/webpack-image-resize-loader#360]
So, TypeScript uses [modules](https://www.typescriptlang.org/docs/handbook/modules.html) for better typing.

If I want to import my TypeScript file, I could import it with `import foo from './bar';`. TypeScript checks the path, recognizes the file `bar.ts` and could retrieve information about the typings of `foo`.

However, if I want to import images, I have to tell TypeScript about those images and declare own modules like `declare module '*.jpg';`. See [this link](https://www.carlrippon.com/using-images-react-typescript-with-webpack5/) for further information.

But now comes the catch. I can import my images with
```typescript
import testImage from 'images/test.jpg';`
```

just fine. But if I want to pass some queries (like resize it to 500px width and change the format to webp) , I have to alter this import.
```typescript
import testImage from 'images/test.jpg?{"width":500, "format": "webp"}';`
```
But now TypeScript modules kick in and fail with `Cannot find module 'images/test.jpg?{"width":500, "format": "webp"}' or its corresponding type declarations.`.

If I tell TypeScript about this module with
```typescript
declare module '*.jpg?{"width":500, "format": "webp"}';
```
then this code works fine. The image gets resized, the format changes to `webp`. But as you can imagine, I don't want to declare modules for every possible image alteration.

Do you know a way to deal with this problem?

**Comment by Calvin-LL** [comment]
Unfortunately it seems like you'll have to do that or use [`// @ts-ignore`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments).

Typescript only allows 1 wildcard in a declaration so `declare module '*.jpg?*'` isn't possible (see: https://stackoverflow.com/questions/56078811/how-can-i-use-multiple-wildcards-in-typescript-module-declarations)

**Comment by ghost** [comment]
I used this declaration now: `declare module '*"format": "webp"}';`

This also enables me to write stuff like `import blorg from 'images/blorg.png?{"quality": 70, "format": "webp"}';`. It might not be the perfect solution, but it works with low efforts.

**Comment by Calvin-LL** [comment]
Thanks for sharing. I can't think of a better way to do this.
