### ISSUE TITLE
Question: Why imagemin?

### ISSUE THREAD

**Issue by coderars** [Calvin-LL/webpack-image-resize-loader#387]
Hi @Calvin-LL !

Thank you for this plugin, I'm using it with great satisfaction, just wondering why the use of `Imagemin` and its dependencies are required (fixed in `package.json`)? Possibly it's the lack of my knowledge - and you use it for reason -, but `Sharp` can [do optimizations by its own](https://sharp.pixelplumbing.com/#optimal), right? Quoted from the link:
> The features of mozjpeg and pngquant can be used to optimise the file size of JPEG and PNG images respectively, without having to invoke separate imagemin processes.

For the images (formats and resize) in my HTML I'm using [@11ty/eleventy-img](https://www.npmjs.com/package/@11ty/eleventy-img) which is based only on `Sharp` and it generates well optimized images (webp, jpg, png), at least Google PageSpeed/Lighthouse and https://webpagetest.org/ likes them.

I'm trying to make the build process of my static site as fast as possible and the fixed `Imagemin` dependencies of this plugin slows it down significantly.

In the docs you already mention it is possible to "disable imagemin for a particular format":
````
{
  imageminOptions: {
    png: null;
  }
}
````
Shouldn't it be the default for all formats and remove the `Imagemin` dependencies? Users could still install these packages by their own when needed and set them in `imageminOptions` as described.

Thank you! 🙇

**Comment by Calvin-LL** [comment]
Looks like `sharp` has added `mozjpeg` and `libimagequant` to its prebuilt binary in [v.28.0](https://sharp.pixelplumbing.com/changelog#v0280---29th-march-2021) since I made this loader. I'll remove `Imagemin` from this loader in the next version. Thanks for letting me know about this issue.
